{{- if not .Values.elasticsearch.secretRef }}
{{- if or .Values.elasticsearch.password .Values.intelligence.apiKey .Values.alerter.slack.webhookUrl }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-seer.fullname" . }}
  labels:
    {{- include "kube-seer.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.elasticsearch.password }}
  ELASTICSEARCH_PASSWORD: {{ .Values.elasticsearch.password | quote }}
  {{- end }}
  {{- if .Values.intelligence.apiKey }}
  INTELLIGENCE_API_KEY: {{ .Values.intelligence.apiKey | quote }}
  {{- end }}
  {{- if .Values.alerter.slack.webhookUrl }}
  ALERTER_SLACK_WEBHOOK_URL: {{ .Values.alerter.slack.webhookUrl | quote }}
  {{- end }}
{{- end }}
{{- end }}
